blueprint: cloudify-dev/blueprint.yaml

task:
  retries: 5
  retry_interval: 1
  thread_pool_size: 20

commands:
  install:
    workflow: install

  pip:
    install:
      workflow: execute_operation
      parameters:
        operation: pip.install
        run_by_dependency_order: true
        type_names: [python_package]

  git:
    status:
      task:
        retries: 0
        retry_interval: 0
        thread_pool_size: 1
      workflow: execute_operation
      parameters:
        operation: git.status
        type_names: [git_repo]
    pull:
      workflow: execute_operation
      parameters:
        operation: git.pull
        type_names: [git_repo]

    checkout:
      args:
        - name: branch
          help: branch name to checkout
      workflow: execute_operation
      parameters:
        operation: git.checkout
        operation_kwargs:
          branch: { arg: branch }
        type_names: [git_repo]
